"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"project_id_env": "CROWDIN_PROJECT_ID"
"preserve_hierarchy": true

"files": [
  {
    "source": "src/main/resources/assets/weaponmod/lang/en_US.lang",
    "translation": "src/main/resources/assets/weaponmod/lang/%language%.lang"
  }
]
