org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

minecraft_version = 1.21.3
minecraft_version_range = [1.21.2,1.21.3]
minecraft_version_condition = >=1.21.2 <=1.21.3
enabled_platforms = fabric,neoforge
parchment_mappings = 2024.12.07

archives_base_name = weaponmod
mod_version = 1.20.0
maven_group = ckathode.weaponmod

architectury_version = 14.0.4
cloth_config_version = 16.0.141
mod_menu_version = 12.0.0-beta.1

fabric_loader_version = 0.16.7
fabric_api_version = 0.106.1+1.21.2

neoforge_version = 21.3.3-beta
neoforge_version_range = [21.2.0-beta,)
loader_version_range = [4,)

mod_id = weaponmod
mod_name = Balkon's WeaponMod: Legacy
mod_license = MIT
mod_group_id = ckathode.weaponmod
mod_authors = BalkondeurAlpha, HyperSpeeed
mod_authors_list = BalkondeurAlpha", "HyperSpeeed
mod_description = Throw a spear in a zombie's head!\nCut a skeleton in half with your brand new halberd!\nShoot some slimes in pieces with an old musket!\nAnd more!
mod_issues_url = https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/issues
mod_sources_url = https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy
mod_home_url = https://www.curseforge.com/minecraft/mc-mods/balkons-weaponmod-legacy
mod_update_json = https://raw.githubusercontent.com/ThexXTURBOXx/UpdateJSONs/master/weaponmod.json
