pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://files.minecraftforge.net/maven/" }
        gradlePluginPortal()
        // TODO: Remove when published officially
        maven { url = "https://femtopedia.de/maven/" }
    }
}

rootProject.name = 'weaponmod'

include 'common'
include 'fabric'
include 'neoforge'
